### PR TITLE
Fixes #22

### LINKED ISSUE #22: Pull for stree ends up in wrong subdir
I gave `stree` a try today, as the basic concept sounds quite fine. Initial splitting and pushing to a remote host with a new bare repository worked fine, unfortunately pulling back changes into the main repo failed in a way, that the changes ended up in a totally unrelated directory. Even worse, the whole subtree got replicated in this other unrelated folder. I had tried to follow the instructions, nevertheless of course, I might have gotten something wrong here, so sorry in advance for that case. The code is closed, so unfortunately I can't directly reference it here. The source tree looks something like:

```
/
/core/...
/utils/...
...
```

This is the sequence of instructions I had used:

```
# on the remote host :
git init --bare utils

# locally in repo root
git stree split utils -P utils code@remotehost:utils
# seemd to work fine
cd ..
git clone code@remotehost:utils utilstest
# everything there, edit edit, commit
git push
# seems to be fine, back to main repo
cd ../testproj
git stree pull utils
```

Now the whole content of utils got replicated into /core/comm/alice and the content there deleted:

```
[master e1bb1e8] [STree] Pulled stree 'utils'
 140 files changed, 12572 insertions(+), 287817 deletions(-)
 create mode 100644 core/comm/alice/__init__.py
 create mode 100644 core/comm/alice/accumarray.py
 delete mode 100644 core/comm/alice/ai.aiml
 delete mode 100644 core/comm/alice/alice.aiml
....
✔ STree 'utils' pulled, 1 update(s) committed.
```
Anything wrong with the path spec there? Any further information I can provide on this, without fully disclosing the whole repo? I was using the latest checokut for this test. This is the stree config:

```
$ git config --list|grep stree
remote.stree-utils.url=code@remotehost:utils
remote.stree-utils.fetch=+refs/heads/master:refs/remotes/stree-utils/master
stree.utils.prefix=utils
stree.utils.branch=master
stree.utils.latest-sync=e1bb1e8
branch.stree-backports-utils.remote=stree-utils
branch.stree-backports-utils.merge=refs/heads/master
```

### PR DESCRIPTION
**Pull request by ml31415**
See related bug report #22 .

### CODE REVIEW

**Comment by ericpollmann** [comment]
Funny, I just noticed this, very similar to the patch I submitted at: https://github.com/tdd/git-stree/pull/32 ---- ml31415 (or is it mlπ?), did you notice merge conflicts after 'git stree pull' into an unchanged stree using this approach?  I'll try it out in my tree and report back...

**Comment by ericpollmann** [comment]
Reporting back: it didn't alter the merge conflicts problem I have, I still get those whether I use:
    git merge --verbose -s recursive -X subtree="$prefix"
-or-
    git merge --verbose -s subtree -X subtree="$prefix"

However, both were better than:
    git merge --verbose -s subtree
This time git merge guessed that the (very small) repo should be merged into / on my tree which deleted >100k files and submitted the change, always a rude surprise.  No wait, it only deleted 65k files, left some behind inexplicably.  How is git merge this bad??

**Comment by ericpollmann** [comment]
I found a way to resolve the conflicts in my case: -Xtheirs -- this works for unchanged tree, which is the vast majority case for my tree (I track dependencies as strees)

To make this optional behavior I am taking the optional args on the 'git stree' commandline, enabling the following workflow (You might notice the failed merge error message is also new, some information on what went wrong...)

$ git stree pull [stree_name]
 ︎✖ Stree '[stree_name]' pulled, conflicts remain which you must merge.
$ git reset --hard HEAD
HEAD is now at a5b7a80 A fantastically interesting commit message.
$ git stree pull [stree_name] -Xtheirs

[master e451d79] [STree] Pulled stree '[stree_name]'
 1375 files changed, 173243 insertions(+), 6029 deletions(-)
...
✔ STree '[stree_name]' pulled, 479 update(s) committed.

I'll send an updated PR later today.

**Comment by ericpollmann** [comment]
Updated PR here, for reference: https://github.com/tdd/git-stree/pull/32

**Comment by stela5** [comment]
I had better luck with https://github.com/tdd/git-stree/pull/32

Here's my full version (including some other features and merge requests): https://gist.github.com/anonymous/5ca8bc8abd59c7006370

Note the `git stree pulltheirs` and `git stree pullours` options

**Comment by tdd** [comment]
Closing this in favor of #32, but 1.0 rewrite makes these PRs blocked for merge anyway. Still, looking at good ideas in there. Thanks all!

**Pull request closed without merging**
