### PR TITLE
2 little bugfixes for git stree split

### PR DESCRIPTION
**Pull request by Yopai**
Hi, I just installed git-stree and start using it. How awesome !

Just found 2 little things I corrected in git stree split :
1) I first got an infinite loop.
For a reason I don't explain, the regexp match ~= always match, even where there is no .. in $path.
I replaced the loop with readlink

2) I got the git error "This command needs to be run in the root directory". So I encapsulate all with pushd/popd.

### CODE REVIEW

**Comment by csemrau** [comment]
Just my 2c: The infinite loop issue is already known, see https://github.com/tdd/git-stree/issues/24. The readlink tool is not available on Git for Windows (at least on my installation).

**Comment by Yopai** [comment]
Thanks for pointing that out, and referencing the bug (I admit I didn't think searching through the bugs)

**Comment by Yopai** [comment]
Just pushed another commit, to avoid readlink :
for existing paths, a simple pushd in the directory will normalize the path.

I didn't analyze code to know if normalize_prefix can be called on non exiting paths, but if the answer is yes, then you can drop the two elsif/else.

**Comment by tdd** [comment]
Hey there,

We're rewriting the normalizing code and beefing it up with tests, so I'm not merging this in, but thanks for bringing the use case to our attention, we'll add it in the tests!

**Pull request closed without merging**
